language: go
install: go get -v github.com/spf13/hugo
script:
  - cd myblog
  - hugo
  - python --version
  - sudo pip install s3cmd
  - s3cmd sync --delete-removed -P -M -r public/ s3://btw-blog/
notifications:
    email:
        on_failure: always