baseURL = "http://myblog.btwsolutions.net"
languageCode = "en-us"
title = "BTW IT Blog"
description = "By The Way did you know I.T."
theme = "hyde-x"


[params]
github = "https://github.com/wrighbr" 
linkedin = "https://www.linkedin.com/in/brett-wright-9384b23a/"

author = "Brett Wright"

searchEngineURL = "https://www.google.com/search"
defaultDescription = "By The Way did you know I.T."

